---

- hosts: rancher
  connection: ssh
  become: yes

  tasks:
    - name: "Install and Run Rancher"
      command: "{{ item }}"
      with_items:
        - "docker pull rancher/rancher:v2.1.0"
        - "docker run -d --name=rancher --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.1.0"
